V_BOX = 'generic/debian12'

VM_PROVIDER = 'virtualbox'

VB_CPU = 1
VB_MEM = 1024

MASTERNODE_MN = 'yohurtebS'

MASTERNODE_IP = '192.168.56.110'

Vagrant.configure("2") do |config|
  config.vm.box = V_BOX

  config.vm.provider VM_PROVIDER do |v|
    v.cpus = VB_CPU
    v.memory = VB_MEM
  end


  config.trigger.before :up do |trigger|
    trigger.run = { inline: "mkdir -p shared confs" }
  end


  config.vm.define MASTERNODE_MN do |control|
    control.vm.hostname = MASTERNODE_MN
    control.vm.network "private_network", ip: MASTERNODE_IP
    control.vm.synced_folder "./shared", "/home/vagrant/shared", type: VM_PROVIDER
    control.vm.synced_folder "./confs", "/home/vagrant/confs", type: VM_PROVIDER
    control.vm.provision "shell", path: "scripts/s_provisioner.sh", env: { "MASTERNODE_IP" => MASTERNODE_IP }
  end

end